joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 436, in _process_worker
    r = call_item()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/externals/loky/process_executor.py", line 288, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 263, in __call__
    for func, args, kwargs in self.items]
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 263, in <listcomp>
    for func, args, kwargs in self.items]
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_validation.py", line 514, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/wrappers/scikit_learn.py", line 157, in fit
    self.model = self.build_fn(**self.filter_sk_params(self.build_fn))
  File "/home/danielco/Downloads/nn-var-cov-pred/src/models/neural_networks.py", line 19, in FFNN
    model.add(Dense(n_neurons, activation=activation))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 210, in add
    self._init_graph_network(self.inputs, self.outputs, name=self.name)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 320, in _init_graph_network
    self.inputs, self.outputs)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1545, in _map_graph_network
    tensor_index=tensor_index)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1532, in build_map
    tensor_index)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1532, in build_map
    tensor_index)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1532, in build_map
    tensor_index)
  [Previous line repeated 960 more times]
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1530, in build_map
    include_arguments=True):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/node.py", line 162, in iterate_inbound
    keras_tensor_arguments)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 536, in map_structure
    expand_composites=expand_composites)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 461, in pack_sequence_as
    0, is_seq)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 405, in _packed_nest_with_indices
    for s in _yield_value(structure):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 165, in _yield_value
    for _, v in _yield_sorted_items(iterable):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/tensorflow_core/python/util/nest.py", line 184, in _yield_sorted_items
    if isinstance(iterable, _collections_abc.Mapping):
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/abc.py", line 139, in __instancecheck__
    return _abc_instancecheck(cls, instance)
RecursionError: maximum recursion depth exceeded in comparison
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/danielco/Downloads/nn-var-cov-pred/src/training/runners.py", line 102, in run_model_training
    verbose=verbose)
  File "/home/danielco/Downloads/nn-var-cov-pred/src/training/optimization.py", line 76, in hyper_params_search
    validation_data=validation_data)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 687, in fit
    self._run_search(evaluate_candidates)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 1468, in _run_search
    random_state=self.random_state))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/sklearn/model_selection/_search.py", line 666, in evaluate_candidates
    cv.split(X, y, groups)))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 1056, in __call__
    self.retrieve()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/parallel.py", line 935, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/home/danielco/miniconda3/envs/dcunhao/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
RecursionError: maximum recursion depth exceeded in comparison
